import { BarChart3, Download } from "lucide-react";
import { notFound } from "next/navigation";
import { Card } from "@/components/ui/card";
import { requireOrganizationAccess } from "@/features/organization/guards";
import { canReviewSubmissions } from "@/features/organization/permissions";
import { getOrganizationStatistics } from "@/features/statistics/queries";

export default async function StatisticsPage({ params }: { params: Promise<{ organizationId: string }> }) {
  const { organizationId } = await params;
  const { user, membership } = await requireOrganizationAccess(organizationId);
  if (!canReviewSubmissions({ systemRole: user.systemRole, membership })) notFound();
  const stats = await getOrganizationStatistics(organizationId);
  return <div><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="flex items-center gap-2 text-sm font-semibold text-indigo-600"><BarChart3 size={18} /> 관리자 통계</p><h1 className="mt-1 text-3xl font-bold">조직 활동 대시보드</h1></div><a className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-indigo-600 px-4 font-semibold text-white" href={`/api/organizations/${organizationId}/statistics.xls`}><Download size={18} /> Excel 다운로드</a></div><div className="mt-6 grid gap-4 sm:grid-cols-4"><Card><p className="text-xs text-slate-500">활성 구성원</p><strong className="text-2xl">{stats.memberCount}</strong></Card><Card><p className="text-xs text-slate-500">채점 완료 응시</p><strong className="text-2xl">{stats.quiz.attempts}</strong></Card><Card><p className="text-xs text-slate-500">퀴즈 평균</p><strong className="text-2xl">{stats.quiz.average?.toFixed(1) ?? "-"}</strong></Card><Card><p className="text-xs text-slate-500">미답변 질문</p><strong className="text-2xl">{stats.questions.unanswered}</strong></Card></div><Card className="mt-5"><h2 className="font-bold">과제 제출률</h2><div className="mt-3 space-y-2">{stats.assignmentRows.map((item) => <div className="flex justify-between gap-4 text-sm" key={item.title}><span>{item.title}</span><strong>{item.submitted}/{item.target} · {(item.rate * 100).toFixed(1)}%</strong></div>)}</div></Card><div className="mt-5 grid gap-5 lg:grid-cols-2"><Card><h2 className="font-bold">퀴즈 문항 정답률</h2><div className="mt-3 space-y-2">{stats.quiz.questions.map((item) => <div className="flex justify-between gap-4 text-sm" key={item.prompt}><span className="line-clamp-1">{item.prompt}</span><strong>{(item.rate * 100).toFixed(1)}%</strong></div>)}</div></Card><Card><h2 className="font-bold">공지 확인률</h2><div className="mt-3 space-y-2">{stats.announcementRows.map((item) => <div className="flex justify-between gap-4 text-sm" key={item.title}><span>{item.title}</span><strong>{item.read}/{item.target} · {(item.rate * 100).toFixed(1)}%</strong></div>)}</div></Card></div><Card className="mt-5"><h2 className="font-bold">질문 응답</h2><p className="mt-2 text-sm text-slate-500">전체 {stats.questions.total}개 · 미답변 {stats.questions.unanswered}개 · 평균 최초 답변 {stats.questions.averageFirstResponseMinutes?.toFixed(1) ?? "-"}분</p></Card></div>;
}
