import { Bell, CalendarDays, ChevronRight, ClipboardList, Home, MessageCircleQuestion } from "lucide-react";

export function ProductPreview() {
  return <div className="relative mx-auto max-w-5xl overflow-hidden rounded-[1.75rem] border border-slate-200 bg-white shadow-2xl shadow-indigo-200/60 dark:border-slate-700 dark:bg-slate-950 dark:shadow-indigo-950/40">
    <div className="flex h-10 items-center gap-2 border-b border-slate-200 bg-slate-50 px-4 dark:border-slate-800 dark:bg-slate-900"><span className="size-2.5 rounded-full bg-red-400"/><span className="size-2.5 rounded-full bg-amber-400"/><span className="size-2.5 rounded-full bg-emerald-400"/><span className="ml-3 rounded-md bg-white px-3 py-1 text-[10px] text-slate-400 shadow-sm dark:bg-slate-800">flow.mvtp.cloud</span></div>
    <div className="grid min-h-[29rem] sm:grid-cols-[11rem_1fr]">
      <aside className="hidden border-r border-slate-200 bg-white p-4 sm:block dark:border-slate-800 dark:bg-slate-950"><strong className="text-sm text-indigo-600">FLOW TASK</strong><nav className="mt-8 space-y-2 text-xs"><span className="flex items-center gap-2 rounded-lg bg-indigo-50 px-3 py-2.5 font-bold text-indigo-700 dark:bg-indigo-950"><Home size={15}/> 홈</span><span className="flex items-center gap-2 px-3 py-2.5 text-slate-500"><ClipboardList size={15}/> 과제</span><span className="flex items-center gap-2 px-3 py-2.5 text-slate-500"><Bell size={15}/> 공지</span><span className="flex items-center gap-2 px-3 py-2.5 text-slate-500"><CalendarDays size={15}/> 일정</span><span className="flex items-center gap-2 px-3 py-2.5 text-slate-500"><MessageCircleQuestion size={15}/> 질문</span></nav></aside>
      <div className="bg-[#f7f7fb] p-5 sm:p-7 dark:bg-slate-900"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold text-indigo-600">대시보드</p><h2 className="mt-1 text-xl font-black sm:text-2xl">준혁님의 조직</h2><p className="mt-1 text-xs text-slate-500">가입한 조직과 진행 중인 과제를 확인합니다.</p></div><div className="size-9 rounded-full bg-indigo-100 ring-4 ring-white dark:bg-indigo-900 dark:ring-slate-800"/></div>
        <div className="mt-6 grid gap-3 sm:grid-cols-3"><PreviewStat label="미제출 과제" value="2" tone="text-red-600"/><PreviewStat label="미확인 공지" value="1" tone="text-amber-600"/><PreviewStat label="이번 주 일정" value="4" tone="text-indigo-600"/></div>
        <div className="mt-6 grid gap-4 lg:grid-cols-[1.35fr_1fr]"><section><div className="flex items-center justify-between"><h3 className="text-sm font-bold">마감이 가까운 과제</h3><span className="text-[10px] font-bold text-indigo-600">전체 보기</span></div><div className="mt-3 space-y-2"><PreviewTask title="웹 해킹 기초 보고서" team="보안 연구부" due="D-2" color="bg-red-50 text-red-600"/><PreviewTask title="7월 활동 회고" team="전체 구성원" due="D-5" color="bg-amber-50 text-amber-600"/><PreviewTask title="다음 주 발표 주제" team="기획부" due="D-8" color="bg-indigo-50 text-indigo-600"/></div></section><section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-700 dark:bg-slate-950"><div className="flex items-center justify-between"><h3 className="text-sm font-bold">최신 공지</h3><Bell size={16} className="text-indigo-600"/></div><p className="mt-4 text-xs font-bold">여름방학 활동 안내</p><p className="mt-2 text-[10px] leading-5 text-slate-500">팀별 활동 일정과 준비물을 확인해 주세요.</p><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800"><div className="h-full w-3/4 rounded-full bg-indigo-500"/></div><p className="mt-2 text-[10px] text-slate-400">12명 중 9명 확인</p></section></div>
      </div>
    </div>
  </div>;
}

function PreviewStat({ label, value, tone }: { label: string; value: string; tone: string }) { return <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-700 dark:bg-slate-950"><p className="text-[10px] text-slate-500">{label}</p><strong className={`mt-1 block text-2xl ${tone}`}>{value}</strong></div>; }
function PreviewTask({ title, team, due, color }: { title: string; team: string; due: string; color: string }) { return <div className="flex items-center justify-between gap-3 rounded-xl border border-slate-200 bg-white p-3 shadow-sm dark:border-slate-700 dark:bg-slate-950"><span className="min-w-0"><strong className="block truncate text-xs">{title}</strong><span className="mt-1 block text-[10px] text-slate-400">{team}</span></span><span className={`flex shrink-0 items-center gap-1 rounded-full px-2 py-1 text-[10px] font-bold ${color}`}>{due}<ChevronRight size={11}/></span></div>; }
