import { QuizQuestionType } from "@prisma/client";
import { ArrowLeft, Library } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { QUIZ_QUESTION_TYPE_LABELS } from "@/constants/quiz";
import { createQuizQuestion, reuseQuizQuestion } from "@/features/quiz/admin-actions";
import { requireOrganizationAccess } from "@/features/organization/guards";
import { canManageOrganization } from "@/features/organization/permissions";
import { prisma } from "@/lib/prisma";

export default async function ManageQuizPage({ params, searchParams }: { params: Promise<{ organizationId: string; assignmentId: string; quizId: string }>; searchParams: Promise<{ error?: string; success?: string }> }) {
  const [{ organizationId, assignmentId, quizId }, query] = await Promise.all([params, searchParams]);
  const { user, membership } = await requireOrganizationAccess(organizationId, true);
  if (!canManageOrganization({ systemRole: user.systemRole, membership })) notFound();
  const quiz = await prisma.quiz.findFirst({ where: { assignmentItemId: quizId, assignmentItem: { assignmentId, assignment: { organizationId, archivedAt: null } } }, select: { title: true, questions: { orderBy: { position: "asc" }, select: { question: { select: { id: true, type: true, prompt: true, points: true, difficulty: true, choices: { orderBy: { position: "asc" }, select: { id: true, content: true, isCorrect: true } } } } } } } });
  if (!quiz) notFound();
  const placedIds = quiz.questions.map(({ question }) => question.id);
  const bank = await prisma.quizQuestion.findMany({ where: { organizationId, id: { notIn: placedIds } }, orderBy: { createdAt: "desc" }, take: 50, select: { id: true, type: true, prompt: true, points: true, difficulty: true, tags: true } });
  return <div className="max-w-5xl"><Link className="inline-flex items-center gap-2 text-sm font-semibold text-slate-500" href={`/organizations/${organizationId}/assignments/${assignmentId}/quiz/${quizId}`}><ArrowLeft size={17} /> 퀴즈로 돌아가기</Link><h1 className="mt-4 text-3xl font-bold">{quiz.title} 문항 구성</h1>{query.error && <p className="mt-4 rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700">문항 작업에 실패했습니다. 입력과 중복 여부를 확인해 주세요.</p>}{query.success && <p className="mt-4 rounded-xl bg-emerald-50 p-3 text-sm font-semibold text-emerald-700">문항 구성을 저장했습니다.</p>}
    <div className="mt-6 grid gap-5 lg:grid-cols-[1.2fr_0.8fr]"><div className="space-y-5"><Card><h2 className="text-lg font-bold">새 문제은행 문항 만들기</h2><p className="mt-1 text-xs text-slate-500">선택지는 한 줄에 하나씩 쓰고 정답 줄 앞에 *를 붙입니다.</p><form action={createQuizQuestion} className="mt-4 space-y-4"><input name="organizationId" type="hidden" value={organizationId} /><input name="assignmentId" type="hidden" value={assignmentId} /><input name="quizId" type="hidden" value={quizId} /><label className="block text-sm">유형<select className="mt-2 min-h-11 w-full rounded-xl border border-slate-200 bg-white px-3 dark:border-slate-700 dark:bg-slate-900" name="type">{Object.values(QuizQuestionType).map((type) => <option key={type} value={type}>{QUIZ_QUESTION_TYPE_LABELS[type]}</option>)}</select></label><label className="block text-sm">문제<textarea className="mt-2 min-h-28 w-full rounded-xl border border-slate-200 bg-white p-3 dark:border-slate-700 dark:bg-slate-900" name="prompt" required /></label><label className="block text-sm">추가 설명<textarea className="mt-2 min-h-20 w-full rounded-xl border border-slate-200 bg-white p-3 dark:border-slate-700 dark:bg-slate-900" name="description" /></label><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">배점<Input className="mt-2" min={0} name="points" required type="number" /></label><label className="text-sm">난이도<Input className="mt-2" name="difficulty" required /></label></div><label className="block text-sm">태그(쉼표 구분)<Input className="mt-2" name="tags" /></label><label className="block text-sm">선택지<textarea className="mt-2 min-h-28 w-full rounded-xl border border-slate-200 bg-white p-3 dark:border-slate-700 dark:bg-slate-900" name="choices" placeholder={'오답\n*정답'} /></label><label className="block text-sm">허용 정답(한 줄에 하나)<textarea className="mt-2 min-h-24 w-full rounded-xl border border-slate-200 bg-white p-3 dark:border-slate-700 dark:bg-slate-900" name="acceptedAnswers" /></label><label className="block text-sm">정답 해설<textarea className="mt-2 min-h-20 w-full rounded-xl border border-slate-200 bg-white p-3 dark:border-slate-700 dark:bg-slate-900" name="explanation" /></label><div className="grid gap-2 sm:grid-cols-3"><label className="text-sm"><input defaultChecked name="required" type="checkbox" /> 필수</label><label className="text-sm"><input name="caseSensitive" type="checkbox" /> 대소문자 구분</label><label className="text-sm"><input defaultChecked name="trimWhitespace" type="checkbox" /> 공백 제거</label></div><Button type="submit">문항 생성·추가</Button></form></Card>
      <Card><h2 className="font-bold">현재 문항 {quiz.questions.length}개</h2><div className="mt-3 space-y-3">{quiz.questions.map(({ question }, index) => <div className="rounded-xl bg-slate-50 p-3 text-sm dark:bg-slate-800" key={question.id}><strong>{index + 1}. {question.prompt}</strong><p className="mt-1 text-xs text-slate-500">{QUIZ_QUESTION_TYPE_LABELS[question.type]} · {question.difficulty} · {question.points}점</p>{question.choices.length > 0 && <ul className="mt-2 list-inside list-disc text-xs">{question.choices.map((choice) => <li className={choice.isCorrect ? "font-semibold text-emerald-600" : ""} key={choice.id}>{choice.content}</li>)}</ul>}</div>)}</div></Card></div>
      <Card className="self-start"><h2 className="flex items-center gap-2 font-bold"><Library size={18} /> 문제은행</h2><p className="mt-1 text-xs text-slate-500">같은 조직에서 만든 최근 문항을 재사용합니다.</p><div className="mt-4 space-y-3">{bank.map((question) => <form action={reuseQuizQuestion} className="rounded-xl border border-slate-200 p-3" key={question.id}><input name="organizationId" type="hidden" value={organizationId} /><input name="assignmentId" type="hidden" value={assignmentId} /><input name="quizId" type="hidden" value={quizId} /><input name="questionId" type="hidden" value={question.id} /><strong className="text-sm">{question.prompt}</strong><p className="mt-1 text-xs text-slate-500">{QUIZ_QUESTION_TYPE_LABELS[question.type]} · {question.points}점 · {question.tags.join(", ")}</p><Button className="mt-2" type="submit">이 퀴즈에 추가</Button></form>)}{!bank.length && <p className="text-sm text-slate-500">재사용할 문항이 없습니다.</p>}</div></Card></div></div>;
}
