import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, BellRing, Blocks, CheckCircle2, ClipboardCheck, LockKeyhole, MessageSquareText, ShieldCheck, Sparkles, UsersRound } from "lucide-react";
import adminScreenshot from "../../docs/screenshots/pr-30-system-admin-dashboard.png";
import { ProductPreview } from "@/components/marketing/product-preview";
import { MARKETING_FEATURES, MARKETING_STEPS, PUBLIC_APP_ORIGIN, PUBLIC_LOGIN_URL, PUBLIC_SIGNUP_URL } from "@/features/marketing/content";

export const metadata: Metadata = {
  title: "Flow Task | 동아리 과제·공지 관리",
  description: "동아리의 공지, 과제, 제출, 피드백, 질문과 부서 활동을 관리하는 서비스",
  alternates: { canonical: PUBLIC_APP_ORIGIN },
  openGraph: { title: "Flow Task", description: "동아리 과제·공지 관리", type: "website", locale: "ko_KR", url: PUBLIC_APP_ORIGIN, siteName: "Flow Task" },
};

const FEATURE_ICONS = [ClipboardCheck, BellRing, UsersRound, Blocks];

export default function HomePage() {
  return <main className="overflow-hidden bg-white text-slate-950 dark:bg-slate-950 dark:text-slate-50">
    <header className="fixed inset-x-0 top-0 z-50 border-b border-slate-200/70 bg-white/85 backdrop-blur-xl dark:border-slate-800 dark:bg-slate-950/85"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-5 lg:px-8"><Link href="/" className="flex items-center gap-2 font-black tracking-tight"><span className="flex size-9 items-center justify-center rounded-xl bg-indigo-600 text-lg text-white">F</span><span>FLOW TASK</span></Link><nav aria-label="메인 메뉴" className="hidden items-center gap-7 text-sm font-semibold text-slate-600 md:flex dark:text-slate-300"><a href="#features">기능</a><a href="#how-it-works">이용 방법</a><a href="#security">보안</a></nav><div className="flex items-center gap-2"><Link href={PUBLIC_LOGIN_URL} className="hidden min-h-10 items-center px-3 text-sm font-bold sm:inline-flex">로그인</Link><Link href={PUBLIC_SIGNUP_URL} className="inline-flex min-h-10 items-center rounded-xl bg-indigo-600 px-4 text-sm font-bold text-white shadow-lg shadow-indigo-200 transition hover:-translate-y-0.5 hover:bg-indigo-700 dark:shadow-none">무료로 시작</Link></div></div></header>

    <section className="relative px-5 pb-20 pt-32 lg:px-8 lg:pb-28 lg:pt-40"><div className="absolute inset-x-0 top-0 -z-0 h-[42rem] bg-[radial-gradient(circle_at_50%_0%,rgba(99,102,241,0.20),transparent_62%)]"/><div className="relative mx-auto max-w-5xl text-center"><span className="inline-flex items-center gap-2 rounded-full border border-indigo-200 bg-indigo-50 px-3 py-1.5 text-xs font-bold text-indigo-700 dark:border-indigo-800 dark:bg-indigo-950 dark:text-indigo-300"><Sparkles size={14}/>동아리 운영 도구</span><h1 className="mx-auto mt-7 max-w-4xl text-4xl font-black leading-tight tracking-[-0.04em] sm:text-6xl lg:text-7xl">공지 등록부터 <span className="bg-gradient-to-r from-indigo-600 to-violet-500 bg-clip-text text-transparent">제출 확인까지</span></h1><p className="mx-auto mt-6 max-w-2xl text-base leading-8 text-slate-600 sm:text-lg dark:text-slate-300">공지, 과제, 제출물과 질문을 조직별로 관리합니다.<br className="hidden sm:block"/> 구성원별 제출 및 공지 확인 현황도 조회할 수 있습니다.</p><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><Link href={PUBLIC_SIGNUP_URL} className="inline-flex min-h-13 items-center justify-center gap-2 rounded-2xl bg-indigo-600 px-6 font-bold text-white shadow-xl shadow-indigo-200 transition hover:-translate-y-0.5 hover:bg-indigo-700 dark:shadow-none">회원가입 <ArrowRight size={18}/></Link><Link href={PUBLIC_LOGIN_URL} className="inline-flex min-h-13 items-center justify-center rounded-2xl border border-slate-300 bg-white px-6 font-bold transition hover:bg-slate-50 dark:border-slate-700 dark:bg-slate-900 dark:hover:bg-slate-800">로그인</Link></div><div className="mt-7 flex flex-wrap justify-center gap-x-5 gap-y-2 text-xs text-slate-500">{["웹에서 사용", "모바일·PC 지원", "이메일 인증"].map((item) => <span key={item} className="inline-flex items-center gap-1.5"><CheckCircle2 size={14} className="text-emerald-500"/>{item}</span>)}</div></div><div className="relative mx-auto mt-14 max-w-6xl"><div className="absolute -inset-8 -z-0 rounded-full bg-indigo-300/20 blur-3xl"/><div className="relative"><ProductPreview/></div></div></section>

    <section id="features" className="scroll-mt-20 bg-slate-50 px-5 py-20 lg:px-8 lg:py-28 dark:bg-slate-900"><div className="mx-auto max-w-7xl"><div className="max-w-2xl"><p className="text-sm font-bold text-indigo-600">주요 기능</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">구성원과 관리자가<br/>같은 진행 현황을 봅니다</h2><p className="mt-5 leading-7 text-slate-600 dark:text-slate-300">구성원은 자신에게 공개된 활동을 확인하고, 관리자는 조직 전체의 진행 현황을 조회합니다.</p></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{MARKETING_FEATURES.map((feature, index) => { const Icon = FEATURE_ICONS[index]; return <article key={feature.title} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-950"><span className="inline-flex rounded-2xl bg-indigo-50 p-3 text-indigo-600 dark:bg-indigo-950"><Icon/></span><h3 className="mt-5 text-lg font-bold">{feature.title}</h3><p className="mt-3 text-sm leading-6 text-slate-500">{feature.description}</p></article>; })}</div></div></section>

    <section id="how-it-works" className="scroll-mt-20 px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-[0.8fr_1.2fr] lg:items-start"><div className="lg:sticky lg:top-28"><p className="text-sm font-bold text-indigo-600">이용 순서</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">조직 개설부터<br/>진행 확인까지</h2><p className="mt-5 leading-7 text-slate-600 dark:text-slate-300">조직을 개설하거나 가입한 다음 공지와 과제를 등록합니다.</p></div><ol className="space-y-4">{MARKETING_STEPS.map((step) => <li key={step.number} className="grid gap-4 rounded-3xl border border-slate-200 p-6 sm:grid-cols-[4rem_1fr] sm:p-8 dark:border-slate-800"><span className="text-3xl font-black text-indigo-200 dark:text-indigo-900">{step.number}</span><div><h3 className="text-xl font-bold">{step.title}</h3><p className="mt-2 text-sm leading-7 text-slate-500">{step.description}</p></div></li>)}</ol></div></section>

    <section id="security" className="scroll-mt-20 bg-indigo-950 px-5 py-20 text-white lg:px-8 lg:py-28"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-2 lg:items-center"><div><span className="inline-flex rounded-2xl bg-white/10 p-3 text-indigo-200"><ShieldCheck size={28}/></span><h2 className="mt-6 text-3xl font-black tracking-tight sm:text-4xl">조직별 접근 권한 적용</h2><p className="mt-5 max-w-xl leading-8 text-indigo-100/80">서버가 로그인 상태, 조직 소속과 역할을 확인한 뒤 자료 접근을 허용합니다. 인증 메일과 비밀번호 재설정 링크에는 사용 기한과 요청 횟수 제한을 적용합니다.</p><div className="mt-7 grid gap-3 text-sm sm:grid-cols-2">{["조직별 접근 제어", "비공개 파일 저장", "보안 세션 쿠키", "중요 작업 감사 로그"].map((item) => <span key={item} className="flex items-center gap-2 rounded-xl bg-white/5 p-3"><LockKeyhole size={16} className="text-indigo-300"/>{item}</span>)}</div></div><div className="overflow-hidden rounded-3xl border border-white/15 bg-white p-2 shadow-2xl"><Image src={adminScreenshot} alt="Flow Task 시스템 관리자 대시보드 실제 화면" className="h-auto w-full rounded-2xl" sizes="(max-width: 1024px) 100vw, 50vw"/><p className="px-3 py-2 text-center text-xs text-slate-500">운영 상태와 감사 기록 관리 화면</p></div></div></section>

    <section className="px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto max-w-5xl overflow-hidden rounded-[2rem] bg-gradient-to-br from-indigo-600 to-violet-600 px-6 py-14 text-center text-white shadow-2xl shadow-indigo-200 sm:px-12 dark:shadow-none"><MessageSquareText className="mx-auto"/><h2 className="mt-5 text-3xl font-black sm:text-4xl">조직 활동을<br/>Flow Task에 등록하세요</h2><p className="mx-auto mt-5 max-w-xl text-indigo-100">계정을 만든 뒤 조직을 개설하고 구성원을 초대할 수 있습니다.</p><Link href={PUBLIC_SIGNUP_URL} className="mt-8 inline-flex min-h-13 items-center gap-2 rounded-2xl bg-white px-6 font-bold text-indigo-700 transition hover:-translate-y-0.5">회원가입 <ArrowRight size={18}/></Link></div></section>

    <footer className="border-t border-slate-200 px-5 py-8 dark:border-slate-800"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-4 text-sm text-slate-500 sm:flex-row sm:items-center"><span className="font-black text-slate-700 dark:text-slate-200">FLOW TASK</span><div className="flex flex-wrap gap-5"><Link href="/privacy">개인정보처리방침</Link><Link href={PUBLIC_LOGIN_URL}>로그인</Link><Link href={PUBLIC_SIGNUP_URL}>회원가입</Link></div><span>© 2026 Flow Task</span></div></footer>
  </main>;
}
