import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, BellRing, Blocks, CheckCircle2, ClipboardCheck, LockKeyhole, MessageSquareText, ShieldCheck, Sparkles, UsersRound } from "lucide-react";
import adminScreenshot from "../../docs/screenshots/pr-30-system-admin-dashboard.png";
import { ProductPreview } from "@/components/marketing/product-preview";
import { MARKETING_FEATURES, MARKETING_STEPS, PUBLIC_APP_ORIGIN, PUBLIC_LOGIN_URL, PUBLIC_SIGNUP_URL } from "@/features/marketing/content";

export const metadata: Metadata = {
  title: "Flow Task | 동아리와 팀의 할 일을 한곳에",
  description: "공지, 과제, 제출, 피드백, 질문과 부서 협업을 한곳에서 관리하는 동아리·팀 운영 서비스",
  alternates: { canonical: PUBLIC_APP_ORIGIN },
  openGraph: { title: "Flow Task", description: "동아리와 팀의 할 일을 한곳에", type: "website", locale: "ko_KR", url: PUBLIC_APP_ORIGIN, siteName: "Flow Task" },
};

const FEATURE_ICONS = [ClipboardCheck, BellRing, UsersRound, Blocks];

export default function HomePage() {
  return <main className="overflow-hidden bg-white text-slate-950 dark:bg-slate-950 dark:text-slate-50">
    <header className="fixed inset-x-0 top-0 z-50 border-b border-slate-200/70 bg-white/85 backdrop-blur-xl dark:border-slate-800 dark:bg-slate-950/85"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-5 lg:px-8"><Link href="/" className="flex items-center gap-2 font-black tracking-tight"><span className="flex size-9 items-center justify-center rounded-xl bg-indigo-600 text-lg text-white">F</span><span>FLOW TASK</span></Link><nav aria-label="메인 메뉴" className="hidden items-center gap-7 text-sm font-semibold text-slate-600 md:flex dark:text-slate-300"><a href="#features">기능</a><a href="#how-it-works">이용 방법</a><a href="#security">보안</a></nav><div className="flex items-center gap-2"><Link href={PUBLIC_LOGIN_URL} className="hidden min-h-10 items-center px-3 text-sm font-bold sm:inline-flex">로그인</Link><Link href={PUBLIC_SIGNUP_URL} className="inline-flex min-h-10 items-center rounded-xl bg-indigo-600 px-4 text-sm font-bold text-white shadow-lg shadow-indigo-200 transition hover:-translate-y-0.5 hover:bg-indigo-700 dark:shadow-none">무료로 시작</Link></div></div></header>

    <section className="relative px-5 pb-20 pt-32 lg:px-8 lg:pb-28 lg:pt-40"><div className="absolute inset-x-0 top-0 -z-0 h-[42rem] bg-[radial-gradient(circle_at_50%_0%,rgba(99,102,241,0.20),transparent_62%)]"/><div className="relative mx-auto max-w-5xl text-center"><span className="inline-flex items-center gap-2 rounded-full border border-indigo-200 bg-indigo-50 px-3 py-1.5 text-xs font-bold text-indigo-700 dark:border-indigo-800 dark:bg-indigo-950 dark:text-indigo-300"><Sparkles size={14}/>복잡한 팀 운영을 더 가볍게</span><h1 className="mx-auto mt-7 max-w-4xl text-4xl font-black leading-tight tracking-[-0.04em] sm:text-6xl lg:text-7xl">동아리와 팀의 <span className="bg-gradient-to-r from-indigo-600 to-violet-500 bg-clip-text text-transparent">할 일을 한곳에</span></h1><p className="mx-auto mt-6 max-w-2xl text-base leading-8 text-slate-600 sm:text-lg dark:text-slate-300">공지는 대화방에 묻히고, 과제는 파일로 헤매고 있나요?<br className="hidden sm:block"/> Flow Task에서 안내부터 제출·피드백까지 하나의 흐름으로 관리하세요.</p><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><Link href={PUBLIC_SIGNUP_URL} className="inline-flex min-h-13 items-center justify-center gap-2 rounded-2xl bg-indigo-600 px-6 font-bold text-white shadow-xl shadow-indigo-200 transition hover:-translate-y-0.5 hover:bg-indigo-700 dark:shadow-none">서비스 이용하러 가기 <ArrowRight size={18}/></Link><Link href={PUBLIC_LOGIN_URL} className="inline-flex min-h-13 items-center justify-center rounded-2xl border border-slate-300 bg-white px-6 font-bold transition hover:bg-slate-50 dark:border-slate-700 dark:bg-slate-900 dark:hover:bg-slate-800">기존 사용자 로그인</Link></div><div className="mt-7 flex flex-wrap justify-center gap-x-5 gap-y-2 text-xs text-slate-500">{["설치 없이 웹에서", "모바일·PC 모두", "자체 보안 인증"].map((item) => <span key={item} className="inline-flex items-center gap-1.5"><CheckCircle2 size={14} className="text-emerald-500"/>{item}</span>)}</div></div><div className="relative mx-auto mt-14 max-w-6xl"><div className="absolute -inset-8 -z-0 rounded-full bg-indigo-300/20 blur-3xl"/><div className="relative"><ProductPreview/></div></div></section>

    <section id="features" className="scroll-mt-20 bg-slate-50 px-5 py-20 lg:px-8 lg:py-28 dark:bg-slate-900"><div className="mx-auto max-w-7xl"><div className="max-w-2xl"><p className="text-sm font-bold text-indigo-600">필요한 것만 선명하게</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">할 일을 놓치지 않는 팀은<br/>운영도 다릅니다</h2><p className="mt-5 leading-7 text-slate-600 dark:text-slate-300">학생은 지금 할 일에 집중하고, 관리자는 진행 상태를 한눈에 확인할 수 있게 만들었어요.</p></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{MARKETING_FEATURES.map((feature, index) => { const Icon = FEATURE_ICONS[index]; return <article key={feature.title} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-950"><span className="inline-flex rounded-2xl bg-indigo-50 p-3 text-indigo-600 dark:bg-indigo-950"><Icon/></span><h3 className="mt-5 text-lg font-bold">{feature.title}</h3><p className="mt-3 text-sm leading-6 text-slate-500">{feature.description}</p></article>; })}</div></div></section>

    <section id="how-it-works" className="scroll-mt-20 px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-[0.8fr_1.2fr] lg:items-start"><div className="lg:sticky lg:top-28"><p className="text-sm font-bold text-indigo-600">세 단계면 충분해요</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">처음이어도<br/>헤매지 않게</h2><p className="mt-5 leading-7 text-slate-600 dark:text-slate-300">복잡한 설정 대신, 조직을 만들고 할 일을 등록하는 핵심 흐름에 집중했어요.</p></div><ol className="space-y-4">{MARKETING_STEPS.map((step) => <li key={step.number} className="grid gap-4 rounded-3xl border border-slate-200 p-6 sm:grid-cols-[4rem_1fr] sm:p-8 dark:border-slate-800"><span className="text-3xl font-black text-indigo-200 dark:text-indigo-900">{step.number}</span><div><h3 className="text-xl font-bold">{step.title}</h3><p className="mt-2 text-sm leading-7 text-slate-500">{step.description}</p></div></li>)}</ol></div></section>

    <section id="security" className="scroll-mt-20 bg-indigo-950 px-5 py-20 text-white lg:px-8 lg:py-28"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-2 lg:items-center"><div><span className="inline-flex rounded-2xl bg-white/10 p-3 text-indigo-200"><ShieldCheck size={28}/></span><h2 className="mt-6 text-3xl font-black tracking-tight sm:text-4xl">팀의 자료는 팀 안에서만</h2><p className="mt-5 max-w-xl leading-8 text-indigo-100/80">조직·부서·과제별 권한을 서버에서 다시 확인하고, 비밀 파일과 외부 연동 정보를 보호해요. 이메일 인증, 일회용 복구 링크, 요청 제한과 감사 기록으로 기본기부터 챙겼습니다.</p><div className="mt-7 grid gap-3 text-sm sm:grid-cols-2">{["조직별 접근 제어", "비공개 파일 저장", "보안 세션 쿠키", "중요 작업 감사 로그"].map((item) => <span key={item} className="flex items-center gap-2 rounded-xl bg-white/5 p-3"><LockKeyhole size={16} className="text-indigo-300"/>{item}</span>)}</div></div><div className="overflow-hidden rounded-3xl border border-white/15 bg-white p-2 shadow-2xl"><Image src={adminScreenshot} alt="Flow Task 시스템 관리자 대시보드 실제 화면" className="h-auto w-full rounded-2xl" sizes="(max-width: 1024px) 100vw, 50vw"/><p className="px-3 py-2 text-center text-xs text-slate-500">실제 운영 상태·감사 기록 관리 화면</p></div></div></section>

    <section className="px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto max-w-5xl overflow-hidden rounded-[2rem] bg-gradient-to-br from-indigo-600 to-violet-600 px-6 py-14 text-center text-white shadow-2xl shadow-indigo-200 sm:px-12 dark:shadow-none"><MessageSquareText className="mx-auto"/><h2 className="mt-5 text-3xl font-black sm:text-4xl">팀의 다음 활동부터<br/>Flow Task와 함께하세요</h2><p className="mx-auto mt-5 max-w-xl text-indigo-100">조직을 만들고 구성원을 초대해 첫 공지와 과제를 등록해 보세요.</p><Link href={PUBLIC_SIGNUP_URL} className="mt-8 inline-flex min-h-13 items-center gap-2 rounded-2xl bg-white px-6 font-bold text-indigo-700 transition hover:-translate-y-0.5">무료로 시작하기 <ArrowRight size={18}/></Link></div></section>

    <footer className="border-t border-slate-200 px-5 py-8 dark:border-slate-800"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-4 text-sm text-slate-500 sm:flex-row sm:items-center"><span className="font-black text-slate-700 dark:text-slate-200">FLOW TASK</span><div className="flex flex-wrap gap-5"><Link href="/privacy">개인정보처리방침</Link><Link href={PUBLIC_LOGIN_URL}>로그인</Link><Link href={PUBLIC_SIGNUP_URL}>회원가입</Link></div><span>© 2026 Flow Task</span></div></footer>
  </main>;
}
